### ISSUE TITLE
Undeprecate FEAT_NSVM_SAFE

### ISSUE THREAD

**Issue by leo60228** [p-sam/switch-sys-tweak#1]
The setting was removed in 4.1.0, and Nintendo has begun supernagging newer firmwares.

**Comment by bottmint** [comment]
Did you mean deprecate? Also, this from the readme 

> FEAT_NSVM_SAFE : Mitm's ns:vm->NeedsUpdateVulnerability to always return 0 (enable using web applets on outdated fws) (Deprecated in favor of setting Atmosphère set:sys overrides, by adding the relevant flag in system_settings.ini)

**Comment by leo60228** [comment]
> Deprecated in favor of setting Atmosphère set:sys overrides, by adding the relevant flag in system_settings.ini

That flag no longer exists, so this is necessary again.

**Comment by p-sam** [comment]
@bottmint  he means removing the deprecation notice

@leo60228 sure i'll remove it, anyway there was not point in having such notice before, as this repo is not really geared towards users.
