### ISSUE TITLE
not working Atmosphere 0.10 (9.1.0)

### ISSUE THREAD

**Issue by Neus252** [p-sam/switch-sys-tweak#2]
crashes on bootup 
error desc: std::abort() called (0xffe)

**Comment by p-sam** [comment]
oh yeah you need to update libstratosphere to be able to use it, if atmosphère is updated

**Comment by Neus252** [comment]
its no longer compatible with libstratosphere not able to build.

**Comment by p-sam** [comment]
You'll have to wait until I get around and update my switch then, I'll might do so today or later this week
