### ISSUE TITLE
Global config.ini 

### ISSUE THREAD

**Issue by Skonikol** [p-sam/switch-sys-tweak#4]
Hi. Is it possible to implement a global configuration file for initializing names?

As an example
config/sys-tweak/config.ini

```
[title id1]
name=my custom title name game
author=someone
display_version=X.X.X

[title id2]
name=my custom title name game
author=someone
display_version=X.X.X
```
etc

**Comment by p-sam** [comment]
Hi, yes it's probably feasible to have both however I'm not going to implement it, I prefer the by-folder approach which leads to faster browsing of smaller ini files
