### ISSUE TITLE
sys-tweak crashes sm when booting on 11.0.1

### ISSUE THREAD

**Issue by FlyingBananaTree** [p-sam/switch-sys-tweak#6]
sys-tweak crashes sm (?) when booting on 11.0.1 with fusee-primary, the error doesn't appear when booting atmosphere with hekate fss0

**Comment by cucholix** [comment]
@FlyingBananaTree correct, booting hekate payload from rcm makes sys-tweak works without problems, but it goes fatal with fusse-primary...

**Comment by p-sam** [comment]
Closing this as it doesn't sound like an issue from sys-tweak, and I don't use fusee

**Comment by FlyingBananaTree** [comment]
It was fixed by the ams 0.16.1 git pull

**Comment by p-sam** [comment]
FYI, you don't need to bother opening an issue for that then, because errors are bound to happen pretty much at every AMS update. Whenever I get around to update all the things I use, I also go and update sys-tweak to match the latest AMS version
