### ISSUE TITLE
Will support for more unicode characters be added in the future?

### ISSUE THREAD

**Issue by tomxhachijuroku** [p-sam/switch-sys-tweak#8]
Hi, do you planning to add support for more Unicode characters like:
Latin-1 Supplement
Latin Extended-A
Latin Extended-B
Because when I put "Pokémon" in the "config.ini" file, it only displays "Pok" in the Switch Home menu, so no support for "é" and other none Basic Latin characters, or am I doing something wrong?

**Comment by p-sam** [comment]
Hi, yes you're probably doing something wrong, I can name a game to "Not Pokémon" just fine here. Make sure you save your file with the right encoding, I suggest trying to save it in "UTF-8" with a tool like sublime text or anything that lets you know and control the encoding of the file.
