### ISSUE TITLE
Changing a game's name does not change the order in which games in the All Apps menu are sorted

### ISSUE THREAD

**Issue by Vazkii** [p-sam/switch-sys-tweak#9]
As seen in this image where I changed the NSO NES app to look like Persona 5 Royal:

![image](https://user-images.githubusercontent.com/1794735/111934532-7d421e00-8ab9-11eb-801d-c32411bf433b.png)

TitleID: `0100D870045B6000`
```
[override_nacp]
name=Persona 5 Royal
author=SEGA EUROPE LTD
display_version=1.04
```

EDIT: The same applies to sorting the list by Publisher.

**Comment by p-sam** [comment]
Overlooking the fact that the example looks like a blatant piracy use case, I'm not looking to patching the sort, or hooking on the services that would return a modified list to fix it
